// Code generated by scripts/generate-plugin-registry.sh; DO NOT EDIT.

package registry

import (
	"insylus/internal/pluginhost"
	"insylus/plugins/access"
	"insylus/plugins/agent"
	"insylus/plugins/dashboard"
	"insylus/plugins/devices"
	"insylus/plugins/docker"
	"insylus/plugins/help"
	"insylus/plugins/jellyfin"
	"insylus/plugins/proxmox"
	"insylus/plugins/services"
	"insylus/plugins/topology"
	"insylus/plugins/wake"
)

func Plugins() []pluginhost.Plugin {
	return []pluginhost.Plugin{
		access.New(),
		agent.New(),
		dashboard.New(),
		devices.New(),
		docker.New(),
		help.New(),
		jellyfin.New(),
		proxmox.New(),
		services.New(),
		topology.New(),
		wake.New(),
	}
}
