#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
plugins_dir="$repo_root/plugins"
out="$plugins_dir/registry/registry_gen.go"

mapfile -t plugin_ids < <(
  find "$plugins_dir" -mindepth 2 -maxdepth 2 -name plugin.go -print \
    | sed -E "s#^$plugins_dir/([^/]+)/plugin.go#\\1#" \
    | grep -v '^registry$' \
    | sort
)

{
  echo "// Code generated by scripts/generate-plugin-registry.sh; DO NOT EDIT."
  echo
  echo "package registry"
  echo
  echo "import ("
  echo '	"insylus/internal/pluginhost"'
  for id in "${plugin_ids[@]}"; do
    echo "	\"insylus/plugins/$id\""
  done
  echo ")"
  echo
  echo "func Plugins() []pluginhost.Plugin {"
  echo "	return []pluginhost.Plugin{"
  for id in "${plugin_ids[@]}"; do
    echo "		$id.New(),"
  done
  echo "	}"
  echo "}"
} > "$out"
